// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Calculadora() {
    driver.Navigate().GoToUrl("http://localhost:8181/");
    driver.Manage().Window.Size = new System.Drawing.Size(1532, 813);
    driver.FindElement(By.LinkText("Calculadora")).Click();
    Assert.Equal(driver.FindElement(By.CssSelector("h1")).Text, "Calculadora");
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(8)")).Click();
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(7)")).Click();
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(6)")).Click();
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(12)")).Click();
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(11)")).Click();
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(10)")).Click();
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(16)")).Click();
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(15)")).Click();
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(14)")).Click();
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(19)")).Click();
    Assert.Equal(driver.FindElement(By.Id("txtPantalla")).Text, "9876543210");
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(20)")).Click();
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(14)")).Click();
    Assert.Equal(driver.FindElement(By.Id("txtPantalla")).Text, "9876543210,1");
    driver.FindElement(By.CssSelector(".btnDigito:nth-child(18)")).Click();
    Assert.Equal(driver.FindElement(By.Id("txtPantalla")).Text, "-9876543210,1");
    driver.FindElement(By.Id("btnBorrar")).Click();
    driver.FindElement(By.Id("btnBorrar")).Click();
    driver.FindElement(By.Id("btnBorrar")).Click();
    Assert.Equal(driver.FindElement(By.Id("txtPantalla")).Text, "-987654321");
    driver.FindElement(By.Id("btnIniciar")).Click();
    Assert.Equal(driver.FindElement(By.Id("txtPantalla")).Text, "0");
  }
}
